### ISSUE TITLE
Dataset Availability

### ISSUE THREAD

**Issue by shubhamtrehan** [Thaonguyen3095/affordance-language#5]
The paper mentions about the dataset of object images and the textual commands. Is that dataset released?

Also I tried to run the code, it says image_label.json file missing
![image](https://github.com/Thaonguyen3095/affordance-language/assets/40584612/4fb3ea30-f3a5-4376-803d-f7366f00c8c3)

In the repo it says to get the dataset run gen_data.py. When I ran that I get following issue
![image](https://github.com/Thaonguyen3095/affordance-language/assets/40584612/a6b8edc9-8f40-4413-83ad-8e90190b3fd3)
I am not sure what another file is missing.

I am just trying to get the dataset

**Comment by Thaonguyen3095** [comment]
As stated in a comment in the resnet.py file, the image_label.json file is generated by running the utils/imagenet.py file. You will have to download and specify your own path to the ILSVRC2012 validation images and image labels to be able to run this file.
Since you haven't successfully ran resnet.py to generate object-embedding.csv, that is what is generating the second error you're getting.
